
CREATE TABLE "TEST_FLIGHT_LEVEL"."FLIGHT_LEVEL"
(
   ACID              VARCHAR(14),
   ORIG              VARCHAR(8),
   DEST              VARCHAR(8),
   OPSDAY            DATE,
   CORNERPOST        VARCHAR(8),
   DEPT_TIME         TIMESTAMP WITH TIME ZONE,
   ARR_TIME          TIMESTAMP WITH TIME ZONE,
   LAST_FILED_DIST   NUMBER,
   BEFORE_ENTRY_DIST NUMBER,
   FLOWN_DIST        NUMBER,
   ARTCC_LEVEL       VARCHAR(8)
);


